from pydantic import BaseModel, ConfigDict, Field, field_validator


class GenerateRequest(BaseModel):
    """Validated request body for content generation."""

    prompt: str = Field(
        ...,
        min_length=1,
        max_length=8000,
        description="User prompt used to generate content.",
        examples=["Write a concise product description for an AI note-taking app."],
    )

    @field_validator("prompt")
    @classmethod
    def prompt_must_not_be_blank(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("Prompt cannot be empty.")
        return cleaned

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "prompt": "Write a short LinkedIn post about responsible AI adoption."
            }
        }
    )


class GenerateResponse(BaseModel):
    """Successful response returned by the generation endpoint."""

    generated_text: str = Field(
        ...,
        description="Text generated by the configured Groq model.",
        examples=["Responsible AI adoption starts with clear goals, strong guardrails, and human review."],
    )
    status: str = Field("success", examples=["success"])

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "generated_text": "Responsible AI adoption starts with clear goals, strong guardrails, and human review.",
                "status": "success",
            }
        }
    )


class HealthResponse(BaseModel):
    """Health check response."""

    status: str = Field("healthy", examples=["healthy"])
